### ISSUE TITLE
[Python2] `int() Can't convert non-string with explicit base`

### ISSUE THREAD

**Issue by jfessard** [abaker/emu2influx#3]
Hi, Every time I run, after a few minutes, it hits that error and just completely stops running altogether. (I have to `kill -9` the python2 process)
Any idea what it could be? Maybe some bad data comes in the serial once in a while and breaks it?
Running from direct command line on ubuntu, `Python 2.7.17 (default, Jul 20 2020, 15:37:01)`

Apart from that, the tool is perfect!
```
Traceback (most recent call last):
  File "./emu2influx.py", line 127, in <module>
    main(client=emu(args.serial_port), db=influx)
  File "./emu2influx.py", line 65, in main
    timestamp = get_timestamp(instantaneous_demand)
  File "./emu2influx.py", line 16, in get_timestamp
    return datetime.utcfromtimestamp(Y2K + int(obj.TimeStamp, 16)).isoformat()
TypeError: int() can't convert non-string with explicit base
```

**Comment by jfessard** [comment]
For extra details. I had it print `obj.TimeStamp` and it sometimes comes up as `None`. I think it that measurement should get skipped in the try block maybe?

```
0x270070c0
0x270070cf
0x270070cf
0x270070de
None
```


Quick and dirty hack that seems to work:
```diff
diff --git a/emu2influx.py b/emu2influx.py
index 24ce166..7abbbcd 100644
--- a/emu2influx.py
+++ b/emu2influx.py
@@ -13,6 +13,9 @@ uint_max = 2**32-1
 
 
 def get_timestamp(obj):
+    if obj.TimeStamp is None:
+        obj.TimeStamp = "0x0"
     return datetime.utcfromtimestamp(Y2K + int(obj.TimeStamp, 16)).isoformat()
```
